site:
  title: Antora ARC42 Template
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://anoff.github.io/antora-arc42
  start_page: system::03_system_scope_and_context.adoc
content:
  sources:
  - url: https://github.com/anoff/antora-arc42.git
    start_path: docs
    branches: [master]
  - url: https://github.com/anoff/antora-arc42-mediaman.git
    start_path: docs
    branches: [master]
ui:
  bundle:
    # url: /developer/anoff/antora-arc42-ui/build/ui-bundle.zip # local
    url: https://github.com/anoff/antora-arc42-ui/releases/download/1.0/ui-bundle.zip
asciidoc:
  attributes:
    sectanchors: true
    plantuml-server-url: http://www.plantuml.com/plantuml
    plantuml-fetch-diagram: true
    imagesoutdir: temp_image/
  extensions:
  - asciidoctor-plantuml
output:
  dir: dist/